# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ab42d2064a0b5af44359cb62d1c9365e2d0001a62249f02fade59097b58da9f48c3e42b511365d237d8f0f9c40ba2985b1027f1ddeb01e3f29e4d241eaa3ab7

test:
  secret_key_base: 93385e797d964a9fe3ecbc2e271c776d692e017048cb9fef952286889bce79191c3f6e746f5c26e946d2dfea16c6ccded7133854a80794cc50217f9e0a4b8bd5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
